title: Kromey's Adventures
description: Just a nerd with aspirations to delusions of grandeur

nav_menu:
  - label: Home
    url: /
  - label: Categories
    url: /category/
    sub_menu:
      - label: Tech
        url: /category/tech/
      - label: '- Security'
        url: /category/security/
      - label: '- How to'
        url: /category/how-to/
      - label: Games
        url: /category/games/
      - label: Life
        url: /category/life/
      - label: Reviews
        url: /category/reviews/
      - label: Updates
        url: /category/updates/
      - label: Random
        url: /category/random/
  - label: About Kromey
    url: /about/
    sub_menu:
      - label: "Kromey's CV"
        url: /about/cv/

#github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-dinky
gfm_quirks: paragraph_end

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

repository: Kromey/Kromey.github.io
timezone: America/Anchorage

paginate: 10
paginate_path: "/page:num/"

collections:
  category:
    output: true
  tag:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: tag
    values:
      layout: "tag"

# These are set by Github and can't be changed
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
