#github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-dinky
gfm_quirks: paragraph_end

plugins:
  - jemoji
  - jekyll-redirect-from

repository: Kromey/Kromey.github.io
timezone: America/Anchorage

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# These are set by Github and can't be changed
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
